Comment on offers
digitalfabrik/integreat-compass pull request #106
Opened 2023-08-21 12:41 UTC by charludo

### Short description

Add ability to comment on offers, and show those comments below offers.

### Proposed changes

- add commenting field for users with the required permission
- use ajax to post comments
- show a hint when a comment was made for an outdated offer version
- **fix** a bug where the state of new offer versions was not reset to PENDING (mist likely introduced in #70)

### Side effects

- none that I could find

### Resolved issues

Fixes: #41

2023-08-31 11:49 UTC, JoeyStk requested changes
Thank you very much for this PR! It's a cool feature!
As far as I know all of the details and permissions work as expected. I only have a few minor comments below :)

2023-08-31 11:49 UTC, JoeyStk commented on integreat_compass/cms/templates/overlay/offer-detail-overlay.html
> +                        <div class="mb-4">
```suggestion
                        <div class="my-4">
```
This is quite picky, but I would personally prefer for the two columns to start on the same height :sweat_smile: but feel free to disagree :blush:

2023-08-31 11:49 UTC, JoeyStk commented on integreat_compass/cms/fixtures/test_data.json
Nice!

2023-08-31 11:49 UTC, JoeyStk commented on integreat_compass/cms/templates/overlay/offer-detail-overlay.html
> +                </div>
```suggestion
                </div>
         {% endif %}
```
Of course only, if you choose to follow my suggestion above

2023-08-31 11:49 UTC, JoeyStk commented on integreat_compass/cms/templates/overlay/offer-detail-overlay.html
> +                <div class="md:flex justify-left gap-12">
```suggestion
{% if public_version %}
                <div class="md:flex justify-left gap-12">
```
Admittedly  this is only an issue for the root user, which we don't really need to pay attention to, but the root user can access this section also via "Application > Details" (The board members are filtered out via next permission check in the next line) and in this view this section doesn't fully work, because max_comment_length doesn't exist for this view. Again this is not really an issue for non-developer-user, but since there is an easy fix for it by excluding non public versions, I say we add it?

2023-08-31 11:49 UTC, JoeyStk commented on integreat_compass/cms/forms/__init__.py
> +from .interactions.report_form import ReportForm
Thanks for cleaning up after me! :see_no_evil:

2023-08-31 11:49 UTC, JoeyStk commented on integreat_compass/cms/urls/protected.py
> +        include([path("add/", interactions.add_comment, name="add_comment")]),
I noticed that I, as any user (not logged in, board member, integration specialist & offer provider) can access this url (and get a blank page). This is where I'm unsure - is this harmless?

2023-08-31 11:49 UTC, JoeyStk commented on integreat_compass/locale/de/LC_MESSAGES/django.po
> +msgstr "Vermerk zur Maßnahme hinzufügen"
```suggestion
msgstr "Kommentar zur Maßnahme hinzufügen"
```
It's surely not incorrect to use "Vermerk", but I personally and the design prefer "Kommentar". I think that in the end it's up to you :)

2023-09-04 15:04 UTC, charludo commented on integreat_compass/cms/templates/overlay/offer-detail-overlay.html
> +                <div class="md:flex justify-left gap-12">
Good catch & nice fix!!

2023-09-04 15:04 UTC, charludo commented on integreat_compass/cms/forms/__init__.py
> +from .interactions.report_form import ReportForm
no worries 😂

2023-09-04 15:07 UTC, charludo commented on integreat_compass/locale/de/LC_MESSAGES/django.po
> +msgstr "Vermerk zur Maßnahme hinzufügen"
While I do agree, apparently this has been requested explicitly (see the very end of the issue description)

2023-09-04 15:08 UTC, charludo commented on integreat_compass/cms/urls/protected.py
> +        include([path("add/", interactions.add_comment, name="add_comment")]),
good catch! No, I think that should not be possible 😅

2023-09-05 07:34 UTC, JoeyStk commented on integreat_compass/locale/de/LC_MESSAGES/django.po
> +msgstr "Vermerk zur Maßnahme hinzufügen"
Ah sorry, that is on me :see_no_evil:

2023-09-05 07:38 UTC, JoeyStk approved these changes
Thank you! :tada:

2023-09-06 05:55 UTC, merged