Add details overlay to applications
digitalfabrik/integreat-compass pull request #108
Opened 2023-08-21 12:59 UTC by JoeyStk

### Short description
This PR adds the detail overlay for offers to the application section. I tried to stay DRY and reuse the already existing overlay for the public offers. However the solution we thought of last week didn't work as expected and therefore I went back to the dirty version. Your suggestions on how to get rid of some of the duplicate code are very welcome! 

### Proposed changes

- Extend the detail offer view to the application process 

### Side effects

- I think none 

### Resolved issues

Fixes: #87

2023-08-21 13:12 UTC, charludo commented
Thank you! 🎉 

> However the solution we thought of last week didn't work as expected and therefore I went back to the dirty version.

Could you elaborate a bit on the issue? 😅

2023-08-22 07:54 UTC, JoeyStk commented
> Could you elaborate a bit on the issue? 😅

After thinking about this again today and a bit more critically I found a way to reuse all of the code by simply creating a new variable called offer_version which in one cases is equal to offer.public_version and in the other to offer.latest_version. With this we can use the same template in both cases. It's embarrassing that I didn't think of it yesterday :see_no_evil:

2023-08-23 08:11 UTC, charludo requested changes
Very nice!

I am experiencing the following issue though: In the applications list, the uppermost offer opens the "details" overlay when clicking the "details" button. For all other offers, nothing happens when pressing the button.
The reason is a mismatch between button and overlay IDs: in the `vote_form.html` template, you use the `offer_version.id` for the id of the details buttons, in `offer-detail-overlay.html` you use the `offer.id` as the id.
(And funnily enough the first pending offer in the view is version 1 of offer 1 😄)

2023-08-23 08:11 UTC, charludo commented on integreat_compass/static/src/js/offer-details.ts
> +        }
Awesome 🎉

2023-08-23 08:44 UTC, JoeyStk commented
> The reason is a mismatch between button and overlay IDs: in the vote_form.html template, you use the offer_version.id for the id of the details buttons, in offer-detail-overlay.html you use the offer.id as the id.

Ohh crap. Yes, this is a remaining issue from what I had tried earlier. Good catch! It should be fixed now. Now I'm matching the offers to each other :sweat_smile: 

Also this PR is blocked until https://github.com/digitalfabrik/integreat-compass/pull/105 is merged, because for reports we also have a details button that should open the overlay

2023-08-23 08:47 UTC, charludo commented
> Also this PR is blocked until #105 is merged, because for reports we also have a details button that should open the overlay

Also if you are already on this template topic, would you mind adding the title image to the vote forms as well? 😅 Just saw that in the initial designs it's included there

2023-08-23 09:21 UTC, JoeyStk commented
@charludo This PR is now ready for review with all discussed extras :grin:

2023-08-23 15:03 UTC, charludo approved these changes
Thank you! Works perfectly now

2023-08-24 08:01 UTC, merged