Setup Testing
digitalfabrik/integreat-compass pull request #24
Opened 2023-04-19 11:40 UTC by SteffiStuffel

### Short description
Added testing config 

### Side effects
Changed SCRIPT_PATH calculation, because it otherwise looked for the script at the wrong place. Tested the other script, should work as expected, but it is not reall nice to hard code `tools` folder name here. Any better ideas?

### Resolved issues

Fixes: #6

2023-04-19 12:02 UTC, timoludwig requested changes

2023-04-19 12:02 UTC, timobrembeck commented on tools/utils/_functions.sh
> +SCRIPT_PATH="${BASE_DIR[0]}/tools/${SCRIPT_NAME}"
> Changed SCRIPT_PATH calculation, because it otherwise looked for the script at the wrong place. Tested the other script, should work as expected, but it is not reall nice to hard code tools folder name here. Any better ideas?

Maybe change the variables above?
```
DEV_TOOL_DIR=$(pwd)
cd ../..
```
to
```
cd ..
DEV_TOOL_DIR=$(pwd)
cd ..
```
or something similar? Then we can rely on the fact that `DEV_TOOL_DIR` is really the dev tool dir, in case we copy more dev tools from integrat-cms...

and keep this  line as it was?

```suggestion
SCRIPT_PATH="${DEV_TOOL_DIR}/${SCRIPT_NAME}"
```

2023-04-19 12:02 UTC, timobrembeck commented on tests/cms/test_dummy.py
> +    assert result == []
```suggestion

def test_dummy(load_test_data):
    pass

```
Maybe this makes more sense as dummy test? This also checks whether the test data has been loaded via the fixture.

2023-04-19 12:02 UTC, timobrembeck commented on tests/conftest.py
> +
```suggestion
```
Can be safely removed I guess. Aiohttp is probably not going to be needed in this project.

2023-04-19 13:04 UTC, timoludwig requested changes

2023-04-19 13:04 UTC, timobrembeck commented on pyproject.toml
> +    "pytest-icdiff==0.6",
These package have quite a few sub-dependencies, so just listing the direct pinned versions is not the desired workflow. Could you instead calculate all installed packages recursively by using my script `./tools/update_dependencies.sh` (after rebasing)?

2023-04-19 13:04 UTC, timoludwig commented on tests/cms/test_dummy.py
> +    pass
```suggestion
def test_dummy(load_test_data):
    pass

```
I think newlines at end of files should always be present

2023-04-20 06:28 UTC, SteffiStuffel commented on pyproject.toml
> +    "pytest-icdiff==0.6",
Thanks, I did this. Can you please explain (or share a link) why this is done?

2023-04-20 09:26 UTC, timobrembeck commented on pyproject.toml
> +    "pytest-icdiff==0.6",
For the reproducibility of the dev and prod environments.
Typically, python libraries don't pin their versions themselves, but just give a version range they're compatible with, to make sure they don't cause version conflicts when used together with other libraries.
So if we only pin the versions of the direct dependencies, the sub-dependencies (and sub-sub etc.) might still have different versions, causing e.g. different behaviours, incompatibilities or breaking changes that are only present on some systems, making it hard to debug the problem and determining its origin.
When pinning the dependencies recursively on the other hand, we can be 100% sure that we have the same packages installed locally, on CircleCI and finally on the production system.

2023-04-20 09:37 UTC, timoludwig approved these changes
Thanks a lot! :muscle:

2023-04-20 09:46 UTC, merged