Add developer documentation
digitalfabrik/integreat-compass pull request #44
Opened 2023-04-21 09:33 UTC by charludo

### Short description

Add developer documentation. The documentation and configs are largely copied from `lunes-cms`

### Proposed changes

- add `make_docs.sh` script and sphinx config files
- add developer documentation 

### Side effects

- I do not think I have sufficient permissions for RTD to create its webhook, so there's no automated builds of any kind ATM.

### Resolved issues

Fixes: #35

2023-04-21 09:53 UTC, timoludwig requested changes
Great, thanks! :100: 

Just a few config problems remain I think.

2023-04-21 09:53 UTC, timoludwig commented on .readthedocs.yaml
> +  os: ubuntu-20.04
```suggestion
  os: ubuntu-22.04
```
Maybe go with the newer LTS version?

2023-04-21 09:53 UTC, timoludwig commented on docs/src/index.rst
> +* :doc:`packaging`: Create an easy installable python
```suggestion
* :doc:`packaging`: Create an easy installable python package
```

2023-04-21 09:53 UTC, timoludwig commented on pyproject.toml
> +    "sphinx-rtd-theme",
Could you execute `./tools/update_dependencies.sh --only=pip` to add these dependencies to the pinned versions as well?

2023-04-21 09:53 UTC, timoludwig commented on .readthedocs.yaml
> +        - doc
```suggestion
        - pinned
        - dev-pinned
```

2023-04-26 10:48 UTC, timoludwig requested changes
Thanks for your changes!
I added the GitHub webhook integration, so pushes on develop and PRs are now built automatically.

The build for this PR however is still failing, maybe you could have a look?
https://readthedocs.org/projects/integreat-compass/builds/20245796/
![Screenshot 2023-04-26 at 12-47-36 integreat-compass Read the Docs](https://user-images.githubusercontent.com/16021269/234552699-91020491-6555-48cb-9143-1727770185e0.png)

Once the build works, the preview of this PR would be available at https://integreat-compass--44.org.readthedocs.build/en/44/

2023-04-26 13:18 UTC, charludo commented
@timoludwig it should be working now: [https://integreat-compass.readthedocs.io/en/add-developer-documentation/index.html](https://integreat-compass.readthedocs.io/en/add-developer-documentation/index.html)

The environment variable `INTEGREAT_COMPASS_INSTALLED`was missing.

Edit: should be back in 5-6 minutes... I don´t know how you built for this branch specifically? I activated builds for this branch in general, but deactivating it again has wiped the documentation

2023-04-26 13:22 UTC, timoludwig commented
> Edit: should be back in 5-6 minutes... I don´t know how you built for this branch specifically? I activated builds for this branch in general, but deactivating it again has wiped the documentation

Pushing to this branch should automatically trigger the PR build again...
Could you resolve the conflicts and squash the commits?

2023-04-26 13:43 UTC, timoludwig commented
This looks cool! https://integreat-compass--44.org.readthedocs.build/en/44/

Could you squash the two commits?

2023-04-26 13:48 UTC, charludo commented
Oh whoops, of course.

2023-04-26 13:50 UTC, timoludwig approved these changes
:rocket:

2023-04-26 13:51 UTC, merged